### ISSUE TITLE
make experiment hashing stable between instances of python

### ISSUE THREAD

**Issue by octopuscabbage** [octopuscabbage/smallab#21]
python's built in hash function is not stable between invocations of python. It would be nice for the hashed name to be stable for various quality of life reasons.

**Comment by akumaraguru** [comment]
Would the hashlib library solve this issue?

**Comment by octopuscabbage** [comment]
Yes but cryptographically secure hashes may be too heavyweight for what we want. There has got to be a lightweight non-secure stable hash somewhere in python (preferably standard library)
